server:
  port: 8961
  
security:
  basic:
    enabled: false #开启认证
  user:
    name: user
    password: 123456
    
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/